register_job_seeker:
  path: /job-seeker/register
  controller: App\Controller\RegisterJobSeekerController

register_recruiter:
  path: /recruiter/register
  controller: App\Controller\RegisterRecruiterController

publish_offer:
  path: /publish-offer
  controller: App\Controller\PublishOfferController

index:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: ui/index.html.twig