imports:
  - { resource: services.yaml }

services:
    App\Gateway\JobSeekerGateway: '@App\Adapter\Doctrine\Repository\JobSeekerRepository'
    App\Gateway\RecruiterGateway: '@App\Adapter\Doctrine\Repository\RecruiterRepository'
